"""Turning what a model emitted into what a person reads.

Reasoning models (MiniMax M3, DeepSeek-R1, QwQ, Qwen) emit their
chain-of-thought inside ``<think>…</think>`` tags in the ordinary content
stream, and agent frameworks leak XML tool invocations and EOS tokens into it
too. This module removes both, and it has exactly one rule about how:

    **Never delete text. Only delete tags.**

The one exception is a *matched* pair — an opener and its closer — because that
is the only shape where the model has said unambiguously where its reasoning
ends. Everything else (a stray closer, a doubled closer, a closer whose opener
never arrived, an opener the stream ended inside) costs its own characters and
nothing else.

That rule exists because the boundary marker is **generated by the model and is
therefore unreliable**. A raw capture of the MiniMax wire shows the tags come
from the provider itself, and shows it placing them wrongly: a closer emitted
twice in a row, and a closer landing six words into the answer it was supposed
to precede. The previous design deleted the region between tags and then grew
guesses to survive the consequences — a rule for the omitted opener, and a
"does what's left contain a letter?" test to catch replies that had been eaten
down to a single full stop. Those were treatments for a symptom whose cause was
the deletion. They are gone.

There is one filter, and batch is defined as streaming fed a single fragment
(``filter_text``), so the text a frontend streams and the text it is finally
told to show cannot disagree. They used to, deliberately, and the frontend
would edit a whole reply down to whatever the batch pass had left of it.

What this still cannot do: recover an answer from a *matched* pair whose closer
the model misplaced. Nothing textual can — that shape is identical to correct
tagging. It costs the words before the closer, not the reply.
"""

import re

# Residual tags in released text. Only ever used to scrub a region that turned
# out to be unmatched, where the point is to drop markup and keep prose.
_RESIDUAL_TAG = re.compile(
    r"</?(?:think|thinking|tool_call)>|<invoke\b[^>]*>|</invoke>|"
    r"</?minimax:tool_call>|<\|im_end\|>|<\|eot_id\|>"
)


class ModelTextFilter:
    """Strip reasoning blocks and structural tokens, fragment by fragment.

    Feed it deltas as they arrive and it returns the displayable part of each;
    call :meth:`flush` at end of stream to release anything it was holding
    back. A withheld tail is either a suffix that could still turn out to be a
    tag split across two deltas (``"<thi"`` + ``"nk>"``), or the inside of a
    region whose closer has not arrived yet — and if it never arrives, that
    text is released rather than lost.

    Leading whitespace is trimmed until the first visible output, so a reply
    that opens with a reasoning block doesn't start with blank lines.
    """

    _THINK_OPEN = ("<think>", "<thinking>")
    _THINK_CLOSE = ("</think>", "</thinking>")
    # Regions that are never prose: a leaked tool invocation, whatever the
    # framework spelled it as.
    _DROP_OPEN = ("<tool_call>", "<invoke>", "<minimax:tool_call>")
    _DROP_CLOSE = ("</tool_call>", "</invoke>", "</minimax:tool_call>")
    # Standalone tokens with no region: just remove them.
    _DROPPED = ("<|im_end|>", "<|eot_id|>")

    # A region ends at *its own* closer. Sharing one closer set across the
    # drop tags would end a <tool_call> block at the </invoke> nested inside
    # it and spill the remainder onto the screen.
    _CLOSES = {
        "<think>": _THINK_CLOSE, "<thinking>": _THINK_CLOSE,
        "<tool_call>": ("</tool_call>",), "<invoke>": ("</invoke>",),
        "<minimax:tool_call>": ("</minimax:tool_call>",),
    }

    _ALL_TAGS = _THINK_OPEN + _THINK_CLOSE + _DROP_OPEN + _DROP_CLOSE + _DROPPED

    def __init__(self):
        self._tail = ""
        self._buffer = ""
        self._closers: tuple[str, ...] | None = None   # None = not in a region
        self._emitted = False

    # ── scanning ──────────────────────────────────────────────────────

    @classmethod
    def _find_first(cls, text: str, tags: tuple[str, ...]) -> tuple[int | None, str | None]:
        best_idx, best_tag = None, None
        for tag in tags:
            idx = text.find(tag)
            if idx != -1 and (best_idx is None or idx < best_idx):
                best_idx, best_tag = idx, tag
        return best_idx, best_tag

    @classmethod
    def _partial_tag_tail(cls, text: str) -> str:
        """Longest suffix of *text* that is a proper prefix of some tag."""
        max_len = min(len(text), max(len(t) for t in cls._ALL_TAGS) - 1)
        for length in range(max_len, 0, -1):
            suffix = text[-length:]
            if any(tag.startswith(suffix) for tag in cls._ALL_TAGS):
                return suffix
        return ""

    # ── the machine ───────────────────────────────────────────────────

    def feed(self, fragment: str) -> str:
        """Return the displayable portion of *fragment* (possibly empty)."""
        text = self._tail + (fragment or "")
        self._tail = ""
        out: list[str] = []

        while text:
            if self._closers is not None:
                idx, closer = self._find_first(text, self._closers)
                if idx is None:
                    # Hold the region's text: if no closer ever comes, the
                    # pair was never matched and this is the model's prose.
                    keep = self._partial_tag_tail(text)
                    self._buffer += text[:len(text) - len(keep)] if keep else text
                    self._tail = keep
                    text = ""
                else:
                    # Matched pair — the one shape safe to delete.
                    self._buffer = ""
                    text = text[idx + len(closer):]
                    self._closers = None
                continue

            idx, tag = self._find_first(text, self._ALL_TAGS)
            if idx is None:
                keep = self._partial_tag_tail(text)
                out.append(text[:len(text) - len(keep)] if keep else text)
                self._tail = keep
                text = ""
                continue

            out.append(text[:idx])
            text = text[idx + len(tag):]
            self._closers = self._CLOSES.get(tag)
            # Anything else — an unmatched closer, a stray EOS token — has
            # already cost exactly its own characters. Keep reading.

        return self._show("".join(out))

    def flush(self) -> str:
        """Release whatever is still held, at end of stream.

        A region still open here never got its closer, so it was not a pair
        and its text is the model's answer. A withheld tail never became a
        tag. Both come back out; only leftover markup is scrubbed.
        """
        released = self._buffer + self._tail
        self._buffer = self._tail = ""
        self._closers = None
        if not released:
            return ""
        return self._show(_RESIDUAL_TAG.sub("", released))

    def _show(self, text: str) -> str:
        if not self._emitted:
            text = text.lstrip()
        if text:
            self._emitted = True
        return text


def filter_text(text: str) -> str:
    """Clean a whole response at once.

    Defined as the streaming filter fed one fragment, so the two can never
    diverge — the agreement is arithmetic, not discipline.
    """
    f = ModelTextFilter()
    return (f.feed(text or "") + f.flush()).strip()
